### ISSUE TITLE
6ImageVideo miss match size

### ISSUE THREAD

**Issue by grammers** [aashi7/NearCollision#1]
I'm tying to run your code.
When executing ```/test/6ImageVideo.ipynb``` do I get the following runtime error:
RuntimeError: Error(s) in loading state_dict for VGGNet:
	size mismatch for final_layer.1.weight: copying a param with shape torch.Size([2048, 4704]) from checkpoint, the shape in current model is torch.Size([2048, 2352]).
It is when 6Image6s_027 is loaded.

It works when I run /test/SingelImageVideo.ipynb and /test/multi_stream_prediction.py.

Any idea where the error is?

**Comment by jianxiongcai** [comment]
I met exactly the same problem. 

Note that the VGGNet in /test/6ImageVideo.ipynb is defined as `self.feature_size = 16*7*7*3`. I changed that to `16*7*7*6` as suggested in their paper. I guess this is a typo?

**Comment by aashi7** [comment]
Yes, it should be 16*7*7*6 for 6ImageVideo.
