### ISSUE TITLE
Missing Training Dataset

### ISSUE THREAD

**Issue by visionbike** [aashi7/NearCollision#2]
Hi, I am interested in your work. 

While trying to train your model, I found you '6ImageTraind2.h5' and '6ImageTestd2.h5' for training and validation. Could you please to provide these files or instruct how to produce these file from your provided data?

Thank you a lot.

**Comment by aashi7** [comment]
As mentioned in the README, the training dataset is in `.mat` format.

S.No. | Folder | Recordings
-- | -- | --
1 | mats_nov | Left images, Right images, 3D point cloud, Calibration
2 | mats_dec | Left images, Right images, 3D point cloud, Calibration
3 | mat_stereo_camera | Left images, Right images, Depth Maps from Stereo Camera

You could refer to this python file to extract data from mat files -- https://github.com/aashi7/NearCollision/blob/master/sample_data/extract_data_from_mat.py
